apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: mydeployment
    kind: frontend
spec:
  template:
    metadata:
      name: my-web-deploy
      labels:
        app: web
        type: frontend
    spec:
      containers:
        - name: nginx-deploy
          image: nginx:stable
  replicas: 3
  selector:
    matchLabels:
      type: frontend