apiVersion: v1
kind: ReplicaSet
metadata:
  name: multi-pod
  labels:
    app: myreplicaset
    kind: frontend
spec:
  template:
    metadata:
      name: my-first-pod
      labels:
        app: myFirstPod
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine

        - name: redis
          image: redis

        - name: memcached
          image: memcached
          
         