apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: myreplicaset
    kind: network

    spec:
      containers:
        - name: nginx
          image: nginx:alpine

        - name: redis
          image: redis

        - name: memcached
          image: memcached
          
         