apiVersion: v1
kind: Pod
metadata:
  name: my-pod-as
  labels:
    app: myFirstPod
    type: network
spec:
  containers:
    - name: nginx
      image: nginx
    - name: redis
      image: redis

    - name: memcached
      image: memcached
          
         


  












